<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;

class Booking extends Model
{
    use HasFactory;

    protected $fillable = [
        'from',
        'to'
    ];

    public function bookable() : BelongsTo
    {
        return $this->belongsTo(Bookable::class);
    }

    public function review() : HasOne
    {
        return $this->hasOne(Review::class);
    }

    public function address() : BelongsTo
    {
        return $this->belongsTo(Address::class);
    }

    public function scopeBetweenDates(Builder $builder, $from, $to) : Builder
    {
        return $builder->where('to', '>=', $from)->where('from', '<=', $to);
    }

    public static function findByReviewKey(string $reviewKey) : ?Booking
    {
        return static::where('review_key', $reviewKey)->with('bookable')->get()->first();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($booking) {
            $booking->review_key = Str::uuid();
        });
    }
}
