<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Review extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'content',
        'rating',
        'bookable_id',
        'booking_id'
    ];

    public function bookable() : BelongsTo
    {
        return $this->belongsTo(Bookable::class);
    }

    public function booking() : BelongsTo
    {
        return $this->belongsTo(Booking::class);
    }

    public function getIncrementing()
    {
//        return parent::getIncrementing(); // TODO: Change the autogenerated stub
        return false; // TODO: Change the autogenerated stub
    }

    public function getKey()
    {
//        return parent::getKey(); // TODO: Change the autogenerated stub
        return 'string'; // TODO: Change the autogenerated stub
    }
}
